version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_survey_bot
    restart: always
    environment:
      - DATABASE_URL=mysql+aiomysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    volumes:
      - .:/app
      - ./src/database:/app/src/database
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot_network

  db:
    image: mysql:8.0
    container_name: survey_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  mysql_data: 